# filepath: /Users/kishanmaurya/Development/Backend/TinyUrl/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules

  # redis-master:
  #   image: redis:latest
  #   container_name: redis-master
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--port", "6379"]

  # redis-slave:
  #   image: redis:latest
  #   container_name: redis-slave
  #   ports:
  #     - "6380:6379"
  #   command: ["redis-server", "--port", "6379", "--replicaof", "redis-master", "6379"]  
  
  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  
  # sentinel:
  #   image: redis:latest
  #   container_name: redis-sentinel
  #   depends_on:
  #     - redis-master
  #   ports:
  #     - "26379:26379"
  #   volumes:
  #     - ./sentinel.conf:/etc/redis/sentinel.conf
  #   command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]