# filepath: /Users/kishanmaurya/Development/Backend/TinyUrl/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    depends_on:
      - redis # Ensure Redis starts before the app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Map container port 6379 to host port 6379