apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyurl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tinyurl
  template:
    metadata:
      labels:
        app: tinyurl
    spec:
      containers:
        - name: tinyurl
          image: droiddevgeeks/tinyurl:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              value: "10255"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI